server:
  port: 8087

spring:
  datasource:
    url: jdbc:mariadb://localhost:33306/securitytest
    username: root
    password: 2846
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl